version: "3.7"

volumes:
  mongodb_volume:
  redis_volume:

services:

  notification:
    build: ./app
    container_name: notification-service
    restart: always
    ports:
      - "8000:80"
    environment:
      - TZ=Europe/Moscow
      - BOT_ENV=PROD
      - MONGO_NAME=invest
      - MONGO_COLLECTION=notifications
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_BONDS_LIST_CACHE_KEY=notification:bonds:default:received
      - REDIS_BONDS_LIST_CACHE_TTL=86400
      - REDIS_NOTIFICATION_QUEUE=notification:stock:price:received
      - TIME_OUT=4
    depends_on:
      - mongodb
      - redis

  bot:
    build: ./bot
    container_name: notification-bot
    restart: always
    environment:
      - TZ=Europe/Moscow
      - BOT_ENV=PROD
      - SERVER_HOST=notification-service
      - REDIS_NOTIFICATION_QUEUE=notification:stock:price:received
      - SERVER_PORT=80
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - TIME_OUT=4
    depends_on:
      - notification

  mongodb:
    image: mongo:latest
    volumes:
     - mongodb_volume:/data/db
    restart: always

  redis:
    image: "redis:alpine"
    volumes:
      - redis_volume:/data
    restart: always