version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  uvicorn_colored:
    "()": uvicorn.logging.DefaultFormatter
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  uvicorn_access:
    "()": uvicorn.logging.AccessFormatter
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: core/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: core/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  uvicorn_colored:
    formatter: uvicorn_colored
    class: logging.StreamHandler
    stream: ext://sys.stdout

  uvicorn_access:
    formatter: uvicorn_access
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  my_module:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - uvicorn_access
    propagate: no
  uvicorn.error:
    level: INFO
    handlers:
      - uvicorn_colored
    propagate: no

root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]